### ISSUE TITLE
AWS provider incompatibilities

### ISSUE THREAD

**Issue by ToROxI** [jetbrains-infra/terraform-aws-spot-fleet#1]
On AWS provider's version 2.4.0 data source [aws_ami](https://www.terraform.io/docs/providers/aws/d/ami.html) has new required field `owners` 

```hcl
~ /foo/bar » terraform apply
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...

Error: module.test.data.aws_ami.common_ami: "owners": required field is not set

Error: module.test.data.aws_ami.ecs_ami: "owners": required field is not set
```

**Comment by rafabios** [comment]
Got same error, I did a PR:

https://github.com/jetbrains-infra/terraform-aws-spot-fleet/pull/2

**Comment by sugdyzhekov** [comment]
PR merged. The issue should be solved. Thank you!
